### PR TITLE
V9

### LINKED ISSUE #24: Data race when using Async or AsyncResult
Hi! I think I have found a potential issue related to `Async` and `AsyncResult` in the code base. As `Async` executes submitted completion handlers on its own private queue, there is a potential for data races when manipulating shared resources.

### To reproduce

Consider the following test:

```swift
import XCTest
@testable import ConfigCat

class CrashAsyncTests: XCTestCase {
    
    func testNotCrashing() {
        let numberOfAttempts = 10
        let expectation = self.expectation(description: "wait for all attempts to mutate dictionary")
        expectation.assertForOverFulfill = true
        expectation.expectedFulfillmentCount = numberOfAttempts
        for i in 0..<numberOfAttempts {
            var sharedResource = ["": ""]
            let async = Async()
            async.apply {
                sharedResource["\(i)"] = "blargh"
                expectation.fulfill()
            }
            async.complete()
        }
        wait(for: [expectation], timeout: .pi)
    }
    
    func testCrashing() {
        let numberOfAttempts = 10
        let expectation = self.expectation(description: "wait for all attempts to mutate dictionary")
        expectation.assertForOverFulfill = true
        expectation.expectedFulfillmentCount = numberOfAttempts
        var sharedResource = ["": ""]
        for i in 0..<numberOfAttempts {
            let async = Async()
            async.apply {
                sharedResource["\(i)"] = "blargh"
                expectation.fulfill()
            }
            async.complete()
        }
        wait(for: [expectation], timeout: .pi)
    }

}
```

When running the test above with thread sanitizer enabled, one can indeed observe a data race:

Skjermbilde 2022-07-14 kl  15 32 43

In and of itself, one can stipulate that `Async` inherently is not thread safe, which is not necessarily problematic. The issue arises when one is manipulating a shared resources via different instances of `Async` or `AsyncResult`.

One example of this, can be found in the way `AutoPollingPolicy.writeConfigCache|readConfigCache` are called in closures passed to instances of `AsyncResult`. See `AutoPollingPolicy:59`:

```swift
timer.setEventHandler(handler: { [weak self] in
            guard let `self` = self else {
                return
            }

            if self.fetcher.isFetching() {
                self.log.debug(message: "Config fetching is skipped because there is an ongoing fetch request")
                return;
            }

            self.fetcher.getConfiguration()
                .apply(completion: { response in
                    let cached = self.readConfigCache()
                    if let config = response.config, response.isFetched() && config.jsonString != cached.jsonString {
                        self.writeConfigCache(value: config) // <- writing to property on Async's private queue
                        self.onConfigChanged?()
                    }
                    
                    if !self.initialized.getAndSet(new: true) {
                        self.initResult.complete()
                    }
                })
        })
```

and in `AutoPollingPolicy:95`:

```swift
public override func getConfiguration() -> AsyncResult<Config> {
        if self.initResult.completed {
            return self.readCacheAsync()
        }
        
        return self.initResult.apply(completion: {
            return self.readConfigCache() // <- reading from property on Async's private queue
        })
    }
```

While access to properties are enforced some places in the code base with `Synced`, in the said examples the code is inherently not thread safe. It is perhaps unfortunate that a by-effect of `Async`'s implementation leads to dispatching code on otherwise inaccessible queues to code from the outside, such that synchronization is needed.

Another issue is that `AsyncResult` itself is not thread safe. In `AsyncResult:96`:

```swift
public func complete(result: Value) {
        self.result = result // <- assignment on the caller's queue
        super.complete()
    }
```

we can see that `self.result` is assigned the argument of `complete(result:)`. As it is not private, the method will be called on the caller's queue. In `AsyncResult:122`:

```swift
@discardableResult
    public func apply(completion: @escaping (Value) -> Void) -> AsyncResult<Value> {
        self.queue.async {
            if self.state.get().isCompleted() {
                guard let result = self.result else { // <- reading self.result on private queue
                    assert(false, "completion handlers executed on an incomplete AsyncResult")
                    return
                }
                
                completion(result)
            } else {
                self.completions.append({
                    guard let result = self.result else {
                        assert(false, "completion handlers executed on an incomplete AsyncResult")
                        return
                    }
                    
                    completion(result)
                })
            }
        }
        
        return self
    }
```

Thus, it is evident there is a potential for accessing `self.result` on different queues.

Conversely, the property `Async.state` is wrapped in a thread safe container / actor. However, since this is a private property, and it is seemingly only accessed on `Async.queue`, it never had to be wrapped in synchronization code in the first place.

### PR DESCRIPTION
**Pull request by z4kn4fein**
### Describe the purpose of your pull request

Fixed #24 by eliminating the `Async` & `AsyncResult` usage.

After further investigation, it turned out we used a dangerous method to force the underlying asynchronous operations behind a synchronous API. Therefore the Protocol now only supports asynchronous usage with async/await and completion callbacks. 

Synchronous methods are still available as `ConfigCatClient` extensions to support scenarios where they are really needed. Be aware that they are using `DispatchSemaphore` to force synchronous execution.

### Breaking changes
- Protocol methods were renamed. 
  - Completion callback API:
    ```swift
    func getValue<Value>(for key: String, defaultValue: Value, user: ConfigCatUser?, completion: @escaping (Value) -> ())
  
    func getVariationId(for key: String, defaultVariationId: String?, user: ConfigCatUser?, completion: @escaping (String?) -> ())
    func getKeyAndValue(for variationId: String, completion: @escaping (KeyValue?) -> ())
  
    func getAllKeys(completion: @escaping ([String]) -> ())
    func getAllValues(user: ConfigCatUser?, completion: @escaping ([String: Any]) -> ())
    func getAllVariationIds(user: ConfigCatUser?, completion: @escaping ([String]) -> ())
  
    func refresh(completion: @escaping () -> ())
    ```
  - Async/await API:
    ```swift
    func getValue<Value>(for key: String, defaultValue: Value, user: ConfigCatUser?) async -> Value

    func getVariationId(for key: String, defaultVariationId: String?, user: ConfigCatUser?) async -> String?
    func getKeyAndValue(for variationId: String) async -> KeyValue?

    func getAllVariationIds(user: ConfigCatUser?) async -> [String]
    func getAllKeys() async -> [String]
    func getAllValues(user: ConfigCatUser?) async -> [String: Any]

    func refresh() async
    ```
- Synchronous API is not part of the Protocol anymore but it's available as `ConfigCatClient` extension:
  ```swift
  func getValueSync<Value>(for key: String, defaultValue: Value, user: ConfigCatUser? = nil) -> Value

  func getVariationIdSync(for key: String, defaultVariationId: String?, user: ConfigCatUser? = nil) -> String?
  func getKeyAndValueSync(for variationId: String) -> KeyValue?

  func getAllVariationIdsSync(user: ConfigCatUser? = nil) -> [String]
  func getAllKeysSync() -> [String]
  func getAllValuesSync(user: ConfigCatUser? = nil) -> [String: Any]

  func refreshSync()
  ```
- The `useAsyncRefresh` parameter of `PollingModes.lazyLoad()` was removed. Its purpose of letting the user not wait for an asynchronous HTTP call became meaningless. Its name was also misleading.

### Related issues (only if applicable)

- #24 

### Requirement checklist (only if applicable)

- [x] I have covered the applied changes with automated tests.
- [x] I have executed the full automated test set against my changes.
- [x] I have validated my changes against all supported platform versions.
- [x] I have read and accepted the [contribution agreement](https://github.com/configcat/legal/blob/main/contribution-agreement.md).

### CODE REVIEW

File: Sources/ConfigCat/ConfigFetcher.swift [hunk 1]
```diff
@@ -1,195 +1,153 @@
...
-            } else {
-                let response = resp as! HTTPURLResponse
-                if response.statusCode >= 200 && response.statusCode < 300, let data = data {
-                    self.log.debug(message: "Fetch was successful: new config fetched")
-                    if let etag = response.allHeaderFields["Etag"] as? String {
-                        self.etag = etag
+    private func sendFetchRequest(url: String, eTag: String, completion: @escaping (FetchResponse) -> Void) {
+        let request = getRequest(url: url, eTag: eTag)
+        session.dataTask(with: request) { (data, resp, error) in
+                    if let error = error {
```
Comment (hakonk) [inline Sources/ConfigCat/ConfigFetcher.swift:109]: Indentation is off here.

File: Sources/ConfigCat/Mutex.swift [hunk 2]
```diff
@@ -0,0 +1,39 @@
+#if os(Linux)
+import Glibc
+#else
+import Darwin
+#endif
+
+import Foundation
+
+class Mutex {
+    private let mutex: UnsafeMutablePointer<pthread_mutex_t> = UnsafeMutablePointer.allocate(capacity: 1)
```
Comment (hakonk) [inline Sources/ConfigCat/Mutex.swift:10]: What is the rationale behind using `pthread_mutex` vs. other primitives such as `DispatchSemaphore`?

**Comment by hakonk** [comment]
I'm happy the thread safety issues have been addressed! Will attempt to provide feedback where I can

File: Sources/ConfigCat/ConfigService.swift [hunk 3]
```diff
@@ -0,0 +1,181 @@
+import Foundation
+
+class ConfigService {
+    private let log: Logger
+    private let fetcher: ConfigFetcher
+    private let mutex: Mutex = Mutex(recursive: true)
+    private let cache: ConfigCache?
+    private let pollingMode: PollingMode
+    private let cacheKey: String
+    private let initialized: Synced<Bool>
```
Comment (hakonk) [inline Sources/ConfigCat/ConfigService.swift:10]: Wrapping this property in `Synced` is perhaps redundant now that a mutex is employed?

File: Sources/ConfigCat/ConfigCatClient.swift [hunk 4]
```diff
@@ -37,177 +37,232 @@ public final class ConfigCatClient : NSObject, ConfigCatClientProtocol {
...
 
-        if let overrideDataSource = self.overrideDataSource {
+    @objc public func refresh(completion: @escaping () -> ()) {
+        if let configService = configService {
+            configService.refresh(completion: completion)
+        } else {
+            log.warning(message: "The ConfigCat SDK is in local-only mode. Calling .refresh() has no effect.")
+            completion()
+        }
+    }
```
Comment (hakonk) [inline Sources/ConfigCat/ConfigCatClient.swift:145]: In the event of refreshing frequently, is there a mechanism that ensures there is only one request in flight at the same time?

Comment (hakonk) [reply Sources/ConfigCat/ConfigCatClient.swift:145]: After digging a bit, it seems it's handled here, if I understand correctly (`ConfigService:113`).

```swift
private func fetchIfOlder(time: Date, preferCache: Bool = false, completion: @escaping (Config) -> Void) {
        mutex.lock()
        defer {
            mutex.unlock()
        }
        if cachedEntry.isEmpty || cachedEntry.fetchTime > time {
            let json = readConfigCache()
            if !json.isEmpty && json != cachedEntry.jsonString {
                let parseResult = json.parseConfigFromJson()
                switch parseResult {
                case .success(let config):
                    cachedEntry = ConfigEntry(jsonString: json, config: config, eTag: "")
                case .failure(let error):
                    log.error(message: "An error occurred during JSON deserialization. %@", error.localizedDescription)
                }
            }
            if cachedEntry.fetchTime > time {
                completion(cachedEntry.config)
                return
            }
        }
        if preferCache && initialized.get() {
            completion(cachedEntry.config)
            return
        }
        // There's an ongoing fetch, save the callback to call it later when the fetch succeeds.
        if completions != nil {
            completions?.enqueue(item: completion)
            return
        }
        // No fetch is running, initiate a new one.
        completions = MutableQueue<(Config) -> Void>()
        completions?.enqueue(item: completion)
        fetcher.fetch(eTag: cachedEntry.eTag) { response in
            self.processResponse(response: response)
        }
    }
```

**Comment by z4kn4fein** [comment]
> I'm happy the thread safety issues have been addressed! Will attempt to provide feedback where I can

Thank you for the feedback!

File: Sources/ConfigCat/ConfigFetcher.swift (hunk 1 above)
Comment (z4kn4fein) [reply Sources/ConfigCat/ConfigFetcher.swift]: Fixed

File: Sources/ConfigCat/ConfigService.swift (hunk 3 above)
Comment (z4kn4fein) [reply Sources/ConfigCat/ConfigService.swift]: It was also used outside the boundaries of the mutex, but after a second thought it wasn't a big work to make it protected, so I did that and now it's a regular `Bool`.

File: Sources/ConfigCat/ConfigCatClient.swift (hunk 4 above)
Comment (z4kn4fein) [reply Sources/ConfigCat/ConfigCatClient.swift:145]: Yep, that is the part which ensures that only a single fetch is running at one time. I put a bit more detailed comments to that section to make the functionality clearer.

File: Sources/ConfigCat/Mutex.swift (hunk 2 above)
Comment (z4kn4fein) [reply Sources/ConfigCat/Mutex.swift:10]: I did some digging in the synchronisation topic and I found out that it's not recommended to use `DispatchSemaphore` in mutex-like scenarios. Mainly because semaphores are not tied to a thread (like mutexes), so the QoS mechanism could not apply thread priority logic to threads that locks on a semaphore, because there's no way to tell which thread owns it. Chances are low but this could end in thread starvation and deadlocks. 
For the same reason it's not recommended to use them for synchronising async callbacks as we did in `AsyncResult`, so it was an other indicator to get rid of it. :)

**Review by hakonk — APPROVED** [review]
LGTM! Great work!

File: Sources/ConfigCat/Mutex.swift (hunk 2 above)
Comment (hakonk) [reply Sources/ConfigCat/Mutex.swift:10]: @z4kn4fein  A side note to the `Mutex` implementation:

If calls to lock/unlock are not balanced, `pthread_mutex_destroy` will not be successful upon `Mutex.deinit`. That is, if `pthread_mutex_destroy` returns a value other than zero, it failed. This can happen if one locked a mutex, but then forgot to unlock before the mutex was deallocated. While this does not seem to be the issue here as `Mutex.unlock` is called via `defer`, it is perhaps worth mentioning with a comment that particular care has to be taken with respect to the life cycle of `Mutex`. Since the return value of `pthread_mutex_destroy` is not handled now, perhaps one could assert that destroy indeed did work as intended in unoptimized code (e.g. via `assertionFailure`)?

Comment (z4kn4fein) [reply Sources/ConfigCat/Mutex.swift:10]: That's a good point, thanks! I've decorated the mutex with asserts.

**Review by kp-cat — APPROVED** [review]
